### ISSUE TITLE
Enhanced logging

### ISSUE THREAD

**Issue by ShonM** [ShonM/ResqueBundle#21]
Use monolog? Hook events?

**Comment by maddo** [comment]
Would be nice to refactor Worker to properly extend the Resque_Worker, so we can properly override the log function. What do think? Seems like you're not using the resque php cli  from the php-resque library anymore, no?

**Comment by ShonM** [comment]
Definitely agree, and part of that is outlined here; https://github.com/ShonM/php-resque/issues/5

**Comment by maddo** [comment]
Perfect, seems like a clear vector of attack
