### ISSUE TITLE
Allow shortcuts for job classes

### ISSUE THREAD

**Issue by ShonM** [ShonM/ResqueBundle#26]
Via @maddo `AcmeResqueBundle:HelloWorld` resolves to `Acme\ResqueBundle\Jobs\HelloWorldJob`

Easy way: Check for a colon, which would mean it's shortcut notation.

**Comment by maddo** [comment]
You mean being able to change:

``` php
Acme\ResqueBundle\Jobs\HelloWorldJob
```

To:

``` php
AcmeResqueBundle:HelloWorld
```

**Comment by ShonM** [comment]
I like your idea much better, let me edit the issue to reflect that.

**Comment by maddo** [comment]
What did you mean before?

**Comment by ShonM** [comment]
I meant the ability to declare jobs as services and using the service names as the parameter, but shortcut notation is much nicer and doesn't require defining the jobs as services, which keeps the container lighter. Your idea was significantly better than mine :)
