### ISSUE TITLE
Use commands for jobs

### ISSUE THREAD

**Issue by maddo** [ShonM/ResqueBundle#56]
A la [JMSJobQueueBundle](https://github.com/schmittjoh/JMSJobQueueBundle)

Advantages
- Reusing the command infrastructure
- Better logging
- Easier dependency injection
- (easily) manually run via command line
- Facilitated testing of jobs

**Comment by ShonM** [comment]
I definitely wouldn't want to see this as the primary source of jobs, but an alternative to the existing options would be nice (I assume that's what you meant?). So there would be three ways to specify a job class;
- Class name (vanilla)
- Bundle:Name (Symfony notation)
- Command (this proposal)

How do we differentiate then between bundle/job and command notations? Of course utility methods could help despite being ugly... add(), with an addByCommand() for example. Let's try to steer clear of that.

Also implementing this should see two spin-offs:
- Job instance resolver, which takes the input target and finds out how to instantiate it using...
- Job instantiation providers (one for each of the valid notations), which can instantiate the resolved job target

So, take an input string, resolve it, then instantiate it using the appropriate provider. What do you think @maddo ?

**Comment by maddo** [comment]
I think we can do a quick check to see if the command exists without doing the interface resolver. The check should be very straightforward. I'll send a PR in a little bit, let me know what you think.

**Comment by ShonM** [comment]
Code speaks louder than words. If your implementation looks nice and clean,
that works for me!
